# This is a template for config.yaml
# Put your API key, API secret, access token and access token secret
# and put Instagram ID (and name) to check
# Finally you have to rename this file to "config.yaml"

consumer_key: 
consumer_secret: 
access_token: 
access_token_secret: 

users:
  #just an example
  - id: instagramjapan
    name: Instagram Japan
